#index:
#    path: /
#    controller: App\Controller\DefaultController::index



register:
    path: /blog
    controller: App\Controller\RegistrationController::register

check-email:
    path: /check-email
    controller: App\Controller\ResetPasswordController::check-email

reset-password:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::reset-password

request:
    path: /request
    controller: App\Controller\ResetPasswordController::request

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

